#!/usr/bin/env python3
"""Check code if satisfied with linux coding style"""

import sys
import os
import re

from tools.parser import get_parser
from tools.git_diff import get_diff
from tools.cmd import run
from tools.console import Console
from tools.message import get_retry_msg
from tools.constant import GIT_DIFF_CACHED, CHECKPATCH, SPELLFILE

FILE_PATH = f"{os.path.dirname(os.path.realpath(__file__))}"
CHECKPATCH_CMD = [
    f"{FILE_PATH}/{CHECKPATCH}",
    "--codespell",
    f"--codespellfile={FILE_PATH}/{SPELLFILE}",
    "--color=always",
]


def check_result(result):
    """check result of checkpatch.pl

    Args:
        result(str): log of checkpatch.pl execution
    """
    results = re.findall(r"\d+ errors, \d+ warnings, \d+ checks", result)
    if len(results) > 0:
        errors, warnings, checks = map(int, re.findall(r"\d+", results[0]))

        retry_msg = get_retry_msg(GIT_DIFF_CACHED, " ".join(CHECKPATCH_CMD))

        if errors > 0:
            Console.error("[ERROR] " + retry_msg)
            raise Exception("checkpatch.pl error")
        if warnings > 0:
            Console.warn("[WARN] " + retry_msg)


def run_check_patch(diff, verbose=False):
    """Run checkpatch.pl to check coding style

    Args:
        diff(str): git revision diff string
        verbose(bool): show debug log if True.
    """

    try:
        result = run(CHECKPATCH_CMD, input=diff).stdout.decode("cp949")
        if verbose:
            Console.info(result)

        return result

    except FileNotFoundError:
        raise Exception("checkpatch.pl not found.")

    except Exception as e:
        raise Exception(e)


if __name__ == "__main__":

    try:
        parser = get_parser()
        parser.add_argument(
            "files",
            nargs="*",
            metavar="<file>...",
            help="if specified, only consider differences in these files",
        )
        args = parser.parse_args()

        diff = get_diff(cached=True, files=args.files)
        result = run_check_patch(diff, verbose=args.verbose)
        check_result(result)

    except Exception as e:
        print(e)
        sys.exit(1)
